{{- if and ( and .Values.database.tls.cert .Values.database.tls.key ) (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pomerium-console.database.tls.secret" . }}
  labels:
    {{- include "pomerium-console.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ .Values.database.tls.cert | b64enc }}
  tls.key: {{ .Values.database.tls.key | b64enc }}
{{- end }}

{{- if and .Values.database.tls.ca (not .Values.database.tls.existingCASecretKey) }}
---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pomerium-console.database.tls.ca.secret" . }}
  labels:
    {{- include "pomerium-console.labels" . | nindent 4 }}
  annotations:
type: Opaque
data:
  {{ .Values.database.tls.caSecretKey }}: {{ .Values.database.tls.ca  | b64enc }}
{{- end }}
