{{- if and (or .Values.image.pullUsername .Values.image.pullPassword) (not .Values.imagePullSecrets) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pomerium-console.pullSecret.name" . }}
  labels:
    {{- include "pomerium-console.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "pomerium-console.pullSecret.data" . }}
{{- end }}
