apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pomerium-console.fullname" . }}
  labels:
    {{- include "pomerium-console.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- if .Values.tls.enabled }}
    tls_cert_file: /pomerium/cert.pem
    tls_key_file: /pomerium/key.pem
    {{- end }}
    {{- if or .Values.tls.ca .Values.tls.existingCASecret }}
    tls_ca_file: /pomerium/ca.pem
    {{- end }}
    database_url: {{ include "pomerium-console.database.dsn" . }}
    {{- if not .Values.config.databrokerServiceUrl }}
    databroker_service_url: https://pomerium-databroker.{{ .Release.Namespace }}.svc.cluster.local
    {{- end }}
    {{- if not .Values.config.prometheusUrl }}
    prometheus_data_dir: /mnt/prometheus
    {{- end }}
    {{- range $k,$v := .Values.config }}
    {{- if $v }}
    {{ snakecase $k }}: {{ $v }}
    {{- end }}
    {{- end }}
