{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.existingSecret }}
type: Opaque
data:
  password: {{ include "pomerium.redis.password" . | b64enc }}
{{- end -}}
