apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ template "pomerium.cache.name" . }}
    helm.sh/chart: {{ template "pomerium.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cache
  name: {{ template "pomerium.cache.fullname" . }}
  annotations:
 {{- if .Values.cache.deployment.annotations }}
 {{- range $key, $value := .Values.cache.deployment.annotations }}
   {{ $key }}: {{ $value | quote }}
 {{- end }}
{{- else if .Values.annotations }}
 {{- range $key, $value := .Values.annotations }}
   {{ $key }}: {{ $value | quote }}
 {{- end }}
{{- end }}
spec:
  replicas: {{ include "pomerium.cache.replicaCount" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "pomerium.cache.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if not .Values.operator.enabled }}
        checksum/secret: {{ include "pomerium.config.static" . | sha256sum }}
        {{- end }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app.kubernetes.io/name: {{ template "pomerium.cache.name" . }}
        helm.sh/chart: {{ template "pomerium.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - --config=/etc/pomerium/config.yaml
{{- range $key, $value := .Values.extraArgs }}
{{- if $value }}
          - --{{ $key }}={{ $value }}
{{- else }}
          - --{{ $key }}
{{- end }}
{{- end }}
        env:
        - name: SERVICES
          value: cache
{{  include "pomerium.databroker.storage.env" . | indent 8 }}
{{- include "pomerium.sharedEnv" . | indent 8 }}
{{- range $name, $value := .Values.extraEnv }}
        - name: {{ $name }}
          value: {{ quote $value }}
{{- end }}
{{- range $name, $value := .Values.cache.deployment.extraEnv }}
        - name: {{ $name }}
          value: {{ quote $value }}
{{- end }}
{{- if .Values.extraEnvFrom }}
        envFrom:
{{        toYaml .Values.extraEnvFrom | indent 8 }}
{{- end }}
        ports:
          - containerPort: {{ template "pomerium.trafficPort.number" . }}
            name: {{ template "pomerium.grpcTrafficPort.name" . }}
            protocol: TCP
          - containerPort: {{ .Values.metrics.port }}
            name: metrics
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: {{ template "pomerium.grpcTrafficPort.name" . }}
          initialDelaySeconds: 15
        readinessProbe:
          tcpSocket:
            port: {{ template "pomerium.grpcTrafficPort.name" . }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - mountPath: {{ include "pomerium.databroker.storage.clientTLS.path" . }}
            name: databroker-client-tls
{{ include "pomerium.volumeMounts" . | indent 10 }}
      serviceAccountName: {{ template "pomerium.cache.serviceAccountName" . }}
      volumes:
        - name: databroker-client-tls
          secret:
            secretName: {{ include "pomerium.databroker.storage.clientTLS.secret" . }}
{{ include "pomerium.volumes.shared" . | indent 8 }}
{{- $ctx := . }}
{{- $_ := set $ctx "currentServiceName" "cache" }}
{{ include "pomerium.volumes.service" $ctx | indent 8 }}
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
