{{- if .Values.operator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pomerium.operator.electionConfigMap" . }}
  labels:
    app.kubernetes.io/name: {{ template "pomerium.operator.name" . }}
    helm.sh/chart: {{ template "pomerium.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}