{{- if .Values.databroker.pdb.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/name: {{ template "pomerium.databroker.name" . }}
    helm.sh/chart: {{ template "pomerium.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: databroker
  name: {{ template "pomerium.databroker.fullname" . }}-pdp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "pomerium.databroker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: {{ .Values.databroker.pdb.minAvailable }}
{{- end }}
