{{- $configName := default (printf "%s-base" (include "pomerium.fullname" .)) .Values.config.existingConfig }}
{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ template "pomerium.operator.name" . }}
    helm.sh/chart: {{ template "pomerium.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: operator
  name: {{ template "pomerium.operator.fullname" . }}
  annotations:
 {{- if .Values.operator.deployment.annotations }}
 {{- range $key, $value := .Values.operator.deployment.annotations }}
   {{ $key }}: {{ $value | quote }}
 {{- end }}
{{- else if .Values.annotations }}
 {{- range $key, $value := .Values.annotations }}
   {{ $key }}: {{ $value | quote }}
 {{- end }}
{{- end }}
spec:
  replicas: {{ default .Values.replicaCount .Values.operator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "pomerium.operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/values: {{ print .Values | sha256sum }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app.kubernetes.io/name: {{ template "pomerium.operator.name" . }}
        helm.sh/chart: {{ template "pomerium.chart" . }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
{{- end }}
    spec:
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        args: 
          - --base-config-file=/etc/pomerium/config.yaml
          - --ingress-class={{ .Values.operator.config.ingressClass }}
          - --service-class={{ .Values.operator.config.serviceClass }}
          - --metrics-address=:8080
          - --health-address=:8081
          - --pomerium-namespace={{ .Release.Namespace }}
          - --pomerium-deployments={{ template "pomerium.authenticate.fullname" . }}
          - --pomerium-deployments={{ template "pomerium.authorize.fullname" . }}
          - --pomerium-deployments={{ template "pomerium.proxy.fullname" . }}
          - --pomerium-deployments={{ template "pomerium.cache.fullname" . }}
          - --debug={{ .Values.operator.config.debug }}
          - --election-configmap={{ template "pomerium.operator.electionConfigMap" . }}
          - --election-namespace={{ .Release.Namespace }}
          - --election=true
        ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
          - containerPort: 8081
            name: health
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
            scheme: HTTP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - mountPath: /etc/pomerium/
          name: config
      volumes:
      - name: config
        configMap:
          name: {{ $configName }}
      serviceAccountName: {{ template "pomerium.operator.serviceAccountName" . }}
{{- if .Values.extraVolumes }}
{{- toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- end }}