{{- $shouldLookupExistingSecrets := and .Values.config.lookupExistingSecrets (not .Values.config.forceGenerateSharedSecrets) -}}
{{- $existingSharedSecrets := and $shouldLookupExistingSecrets (lookup "v1" "Secret" .Release.Namespace (include "pomerium.sharedSecrets.name" . )) -}}
{{- $existingSharedSecretData := or $existingSharedSecrets.data (dict) -}}
{{- $existing_shared_secret := and $existingSharedSecretData.SHARED_SECRET ((or $existingSharedSecretData.SHARED_SECRET "") | b64dec) -}}
{{- $existing_cookie_secret := and $existingSharedSecretData.COOKIE_SECRET ((or $existingSharedSecretData.COOKIE_SECRET "") | b64dec) -}}
{{- $shared_secret := coalesce .Values.config.sharedSecret $existing_shared_secret (randAscii 32 | b64enc) -}}
{{- $cookie_secret := coalesce .Values.config.cookieSecret $existing_cookie_secret (randAscii 32 | b64enc) -}}

{{- $existingRedisSecret := and $shouldLookupExistingSecrets (lookup "v1" "Secret" .Release.Namespace .Values.redis.existingSecret) -}}
{{- $existingRedisPassword := and $existingRedisSecret ((or (index (or $existingRedisSecret.data (dict)) .Values.redis.existingSecretPasswordKey) "") | b64dec) -}}
{{- $redisPassword := coalesce .Values.redis.password $existingRedisPassword ($shared_secret | sha256sum) -}}

{{/* Render redis scheme */}}
{{- define "pomerium.redis.scheme" -}}
{{- if .Values.redis.tls.enabled -}}
rediss
{{- else -}}
redis
{{- end -}}
{{- end -}}

{{- $redisConnectionString := printf "%s://:%s@%s-master.%s.svc.cluster.local:6379" (include "pomerium.redis.scheme" . ) $redisPassword (include "pomerium.redis.name" . ) .Release.Namespace -}}
{{- $databrokerStorageConnectionString := default (and (eq (include "pomerium.databroker.storage.type" . ) "redis") $redisConnectionString) .Values.databroker.storage.connectionString -}}

{{- $generatingSharedSecrets := and .Values.config.generateSharedSecrets (or .Release.IsInstall .Values.config.forceGenerateSharedSecrets) -}}
{{- $defineSharedSecrets := or $generatingSharedSecrets .Values.config.sharedSecret .Values.config.cookieSecret -}}

{{- if $defineSharedSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ template "pomerium.name" . }}
    helm.sh/chart: {{ template "pomerium.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook-delete-policy: before-hook-creation
{{- if .Values.config.forceGenerateSharedSecrets }}
    helm.sh/hook: pre-upgrade
{{- else if .Values.config.generateSharedSecrets }}
    helm.sh/hook: pre-install
{{- end }}
  name: {{ template "pomerium.sharedSecrets.name" . }}
type: Opaque
data:
{{- if or .Values.config.generateSharedSecrets .Values.config.sharedSecret }}
  SHARED_SECRET: {{ $shared_secret | b64enc | quote }}
{{- end }}
{{- if or .Values.config.generateSharedSecrets .Values.config.cookieSecret }}
  COOKIE_SECRET: {{ $cookie_secret | b64enc | quote }}
{{- end }}
{{- end }}
{{ if and .Values.databroker.storage.autoconfigure (ne (include "pomerium.databroker.storage.type" . ) "memory") }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ template "pomerium.name" . }}
    helm.sh/chart: {{ template "pomerium.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    helm.sh/hook-delete-policy: before-hook-creation
{{- if .Values.config.forceGenerateSharedSecrets }}
    helm.sh/hook: pre-upgrade
{{- else if .Values.config.generateSharedSecrets }}
    helm.sh/hook: pre-install
{{- end }}
  name: {{ template "pomerium.databroker.storage.secret.name" . }}
type: Opaque
data:
  DATABROKER_STORAGE_CONNECTION_STRING: {{ $databrokerStorageConnectionString | b64enc | quote }}
  DATABROKER_STORAGE_TLS_SKIP_VERIFY: {{ .Values.databroker.storage.tlsSkipVerify | toString | b64enc | quote }}
{{- end }}
{{ if .Values.redis.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.existingSecret }}
type: Opaque
data:
  password: {{ $redisPassword | b64enc | quote }}
{{ end -}}
