{{- if and (and .Values.ingressController.enabled (not .Values.ingressController.operatorMode)) .Values.config.insecureProxy -}}
{{ fail "`ingressController.enabled` is not compatible with `config.insecureProxy`" }}
{{- end -}}
{{- if and .Values.ingressController.enabled (not (or .Values.config.generateTLS .Values.authenticate.ingress.tls.secretName )) -}}
{{ fail "A TLS certificate must be available for Authenticate when using the ingress controller.  Please set `config.generateTLS` or `authenticate.ingress.tls.secretName"}}
{{- end -}}
{{- if and (and .Values.ingressController.enabled (not .Values.ingressController.operatorMode)) .Values.ingress.enabled -}}
{{ fail "`ingressController.enabled` is not compatible with `ingress.enabled` unless legacy `ingressController.operatorMode`" }}
{{- end -}}
