apiVersion: v1
kind: Service
metadata:
  name: {{ template "pomerium.proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "pomerium.proxy.name" . }}
    helm.sh/chart: {{ template "pomerium.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: proxy
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
    {{ $annotationExist := false }}
{{- if .Values.service.annotations }}
{{ $annotationExist = true }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
{{- if .Values.proxy.service.annotations }}
{{- if not $annotationsExist }}
{{ $annotationExist = true}}
  annotations:
{{- end }}
{{ toYaml .Values.proxy.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: https
      protocol: TCP
      name: https
    - name: metrics
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: metrics
{{- if hasKey .Values.service "nodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ template "pomerium.proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
